//
//  JourneyAudioAvailability.swift
//  Thaqalayn
//
//  On-demand delivery for premium journey narration (Phase 4.2). The two free journeys
//  (Yaqin, al-Fatiha) ship bundled in the app; every other journey's narration mp3s are
//  Apple-hosted On-Demand Resources (ODR), tagged by journey id, downloaded on the first
//  Listen and then cached by iOS for offline replay. This service owns the NSBundleResourceRequest
//  lifecycle: it reports whether a journey is bundled / downloaded / needs a download / is
//  downloading, drives the "Preparing this journey…" state, and keeps the request alive so
//  the downloaded mp3s resolve through the bundle while the journey plays.
//
//  The ODR tag for a journey is exactly its id (e.g. "surah-rahman"). Each tagged pack is
//  SELF-CONTAINED (all the narration strings that journey speaks, including shared connectors),
//  so a journey downloads and plays as one independent unit with no cross-pack dependencies.
//

import Foundation

@MainActor
final class JourneyAudioAvailability: ObservableObject {
    static let shared = JourneyAudioAvailability()
    private init() {}

    /// Journeys whose narration ships inside the app binary - always available, never an ODR
    /// download. Mirrors the free tier gated by PremiumManager (Yaqin + surah-fatiha).
    static let bundledJourneyIds: Set<String> = ["yaqin", "surah-fatiha"]

    static func isBundled(_ journeyId: String) -> Bool { bundledJourneyIds.contains(journeyId) }

    /// Journey ids whose narration is fully available to Listen: the bundled free tier plus
    /// every complete on-demand pack. Loaded once from the bundled `journey_audio_ready.json`
    /// (regenerated by package_journey_odr.py). The Listen entry is gated on this so a journey
    /// whose audio isn't finished yet never offers a half-silent Listen - it just doesn't appear.
    static let audioReadyJourneyIds: Set<String> = {
        guard let url = Bundle.main.url(forResource: "journey_audio_ready", withExtension: "json"),
              let data = try? Data(contentsOf: url),
              let ids = try? JSONDecoder().decode([String].self, from: data) else {
            return bundledJourneyIds   // fail safe: at least the bundled free journeys are playable
        }
        return Set(ids)
    }()

    /// Whether a journey's narration is complete and ready to Listen (gates the entry).
    static func isAudioReady(_ journeyId: String) -> Bool { audioReadyJourneyIds.contains(journeyId) }

    enum State: Equatable {
        case bundled                        // ships in the app - instant
        case downloaded                     // ODR pack present on device
        case needsDownload
        case downloading(progress: Double)
        case failed(String)
    }

    /// Live state per journey id, for any UI that wants to reflect it (the Listen entry, a
    /// future "downloaded journeys" screen). Bundled journeys are reported without a lookup.
    @Published private(set) var states: [String: State] = [:]

    /// Active ODR requests, kept alive (accessing) while a journey is in use so its mp3s keep
    /// resolving through Bundle.main. Released in `release(journeyId:)` when playback ends.
    private var requests: [String: NSBundleResourceRequest] = [:]

    func state(for journeyId: String) -> State {
        if Self.isBundled(journeyId) { return .bundled }
        return states[journeyId] ?? .needsDownload
    }

    /// Ensure a journey's narration is on device, ready to resolve through the bundle. Bundled
    /// journeys return instantly. Otherwise this begins (or reuses) the ODR request for the
    /// journey's tag, reporting download progress via `onProgress` and the published `states`,
    /// and returns whether the pack is now available. The request is retained so the resources
    /// stay accessible for playback; call `release(journeyId:)` when done.
    func ensureAvailable(journeyId: String, onProgress: @escaping (Double) -> Void = { _ in }) async -> Bool {
        if Self.isBundled(journeyId) { return true }

        // A live, still-accessing request means the pack is ready right now.
        if requests[journeyId] != nil, case .downloaded = states[journeyId] { return true }

        let req = requests[journeyId] ?? NSBundleResourceRequest(tags: [journeyId])
        req.loadingPriority = NSBundleResourceRequestLoadingPriorityUrgent
        requests[journeyId] = req

        // Already downloaded (cached by iOS from a previous Listen)? Access without a network hit.
        if await req.conditionallyBeginAccessingResources() {
            states[journeyId] = .downloaded
            onProgress(1)
            return true
        }

        states[journeyId] = .downloading(progress: 0)
        onProgress(0)
        // Progress fires on an arbitrary thread; marshal to main for the published state + callback.
        // Capture the request's identity (Sendable), not the request itself, so a stale
        // observation from a superseded request is ignored.
        let reqId = ObjectIdentifier(req)
        let observation = req.progress.observe(\.fractionCompleted) { [weak self] progress, _ in
            let p = progress.fractionCompleted
            Task { @MainActor in
                guard let self, let current = self.requests[journeyId],
                      ObjectIdentifier(current) == reqId else { return }
                self.states[journeyId] = .downloading(progress: p)
                onProgress(p)
            }
        }
        defer { observation.invalidate() }

        do {
            try await req.beginAccessingResources()
            states[journeyId] = .downloaded
            onProgress(1)
            return true
        } catch {
            // Failed download: drop the request so a retry starts clean.
            req.endAccessingResources()
            requests[journeyId] = nil
            states[journeyId] = .failed(error.localizedDescription)
            return false
        }
    }

    /// End access to a journey's ODR pack when playback stops. iOS keeps the bytes cached
    /// (eligible for purging only under storage pressure), so a later Listen re-accesses fast
    /// - offline if still cached. Bundled journeys are a no-op.
    func release(journeyId: String) {
        guard let req = requests[journeyId] else { return }
        req.endAccessingResources()
        requests[journeyId] = nil
        if !Self.isBundled(journeyId) { states[journeyId] = .needsDownload }
    }
}
