#!/usr/bin/env python3
"""
Validate Arabic tafsir JSON files generated by the arabic-translator agent.
This script runs as a Claude Code PostToolUse hook.

Non-blocking validation: Errors are printed to stdout as feedback for the agent
to fix, rather than blocking the tool use. The agent sees the errors and can
rewrite the file with corrections.

Exit codes:
- 0: Always (non-blocking) - errors are feedback, not blockers
"""

import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Tuple

# Setup logging to file
LOG_DIR = Path(__file__).parent.parent.parent / "logs"
LOG_FILE = LOG_DIR / "arabic_validator.log"


def log(message: str):
    """Append a timestamped message to the log file."""
    try:
        LOG_DIR.mkdir(exist_ok=True)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(f"[{timestamp}] {message}\n")
    except Exception:
        pass  # Silently fail if logging fails

# Required Arabic layer keys (Arabic-only output format)
REQUIRED_ARABIC_LAYERS = {"layer1_ar", "layer2_ar", "layer3_ar", "layer4_ar", "layer5_ar"}

# Common typos to detect
TYPO_PATTERNS = [
    (r"^layar\d(_ar)?$", "typo 'layar' instead of 'layer'"),
    (r"^layer\d\s+(_ar)?$", "trailing whitespace in key"),
    (r"^Layer\d(_ar)?$", "incorrect capitalization 'Layer' instead of 'layer'"),
    (r"^layer\s+\d(_ar)?$", "space between 'layer' and number"),
    (r"^layre\d(_ar)?$", "typo 'layre' instead of 'layer'"),
    (r"^layer\d_ar_$", "trailing underscore in key"),
    (r"^layer\d_Ar$", "incorrect capitalization '_Ar' instead of '_ar'"),
    (r"^layer\d_AR$", "incorrect capitalization '_AR' instead of '_ar'"),
    (r"^layer\d_arabic$", "use '_ar' not '_arabic'"),
]

# Arabic script Unicode ranges
# - Basic Arabic: \u0600-\u06FF
# - Arabic Supplement: \u0750-\u077F
# - Arabic Extended-A: \u08A0-\u08FF
# - Arabic Presentation Forms-A: \uFB50-\uFDFF
# - Arabic Presentation Forms-B: \uFE70-\uFEFF
ARABIC_PATTERN = re.compile(r'[\u0600-\u06FF\u0750-\u077F\u08A0-\u08FF\uFB50-\uFDFF\uFE70-\uFEFF]')

# Word count limits for Arabic content
MIN_ARABIC_WORDS = 50
MAX_ARABIC_WORDS = 400


def check_duplicate_keys(file_path: str) -> List[str]:
    """
    Check for duplicate keys in a JSON file.
    Python's json.load() silently ignores duplicates, so we need custom parsing.
    Returns a list of error messages for any duplicates found.
    """
    errors = []

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception:
        return []  # File read errors handled elsewhere

    # Track duplicates at each nesting level
    def check_duplicates_hook(pairs: List[Tuple[str, any]]) -> dict:
        """Custom object_pairs_hook to detect duplicate keys."""
        seen = {}
        result = {}
        for key, value in pairs:
            if key in seen:
                # Record the duplicate - we'll extract context later
                seen[key] += 1
            else:
                seen[key] = 1
            result[key] = value

        # Check for duplicates
        for key, count in seen.items():
            if count > 1:
                errors.append(f"Duplicate key '{key}' found {count} times")

        return result

    try:
        json.loads(content, object_pairs_hook=check_duplicates_hook)
    except json.JSONDecodeError:
        pass  # JSON errors handled elsewhere

    return errors


def has_arabic_characters(text: str) -> bool:
    """Check if text contains Arabic script characters."""
    return bool(ARABIC_PATTERN.search(text))


def count_arabic_words(text: str) -> int:
    """
    Count words in Arabic text.
    Arabic uses spaces between words similar to English.
    """
    # Split on whitespace and filter empty strings
    words = [w for w in text.split() if w.strip()]
    return len(words)


def is_arabic_tafsir_file(file_path: str) -> bool:
    """Check if the file is an Arabic tafsir output file in new_tafsir/ directory."""
    path = Path(file_path)
    # Must be in new_tafsir/ directory
    if "new_tafsir" not in str(path):
        return False
    # Match tafsir_*_v*-*_ar.json pattern (e.g., tafsir_103_v1-3_ar.json)
    if re.match(r"tafsir_\d+_v\d+-\d+_ar\.json$", path.name):
        return True
    # Also match legacy _arabic_added.json suffix
    if path.name.endswith("_arabic_added.json"):
        return True
    return False


def extract_expected_verses(file_path: str) -> Optional[List[int]]:
    """
    Extract expected verse range from filename.
    e.g., tafsir_103_v1-3_ar.json → [1, 2, 3]
    Returns None if pattern doesn't match.
    """
    path = Path(file_path)
    match = re.match(r"tafsir_\d+_v(\d+)-(\d+)_ar\.json$", path.name)
    if match:
        start = int(match.group(1))
        end = int(match.group(2))
        return list(range(start, end + 1))
    return None


def validate_arabic_tafsir(file_path: str) -> List[str]:
    """
    Validate an Arabic tafsir file (Arabic-only format).
    Returns a list of error messages (empty if valid).
    """
    errors = []
    path = Path(file_path)

    # Only validate Arabic tafsir files (includes new_tafsir/ directory check)
    if not is_arabic_tafsir_file(file_path):
        return []

    # Check if file exists
    if not path.exists():
        errors.append(f"File does not exist: {file_path}")
        return errors

    # 0. Check for duplicate keys (must be done before json.load which silently ignores them)
    duplicate_errors = check_duplicate_keys(file_path)
    if duplicate_errors:
        errors.extend(duplicate_errors)

    # 1. Parse JSON
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        errors.append(f"Invalid JSON: {e}")
        return errors

    # 2. Root must be object
    if not isinstance(data, dict):
        errors.append(f"Root must be object, got {type(data).__name__}")
        return errors

    if len(data) == 0:
        errors.append("File contains no verses (empty object)")
        return errors

    # 3. Check all expected verses are present (based on filename)
    expected_verses = extract_expected_verses(file_path)
    if expected_verses:
        actual_verses = set(int(k) for k in data.keys() if k.isdigit())
        missing_verses = set(expected_verses) - actual_verses
        if missing_verses:
            missing_sorted = sorted(missing_verses)
            errors.append(f"Missing verses from expected range: {missing_sorted}")

    # 4. Validate each verse
    for verse_key, verse_data in data.items():
        # Check verse key is valid integer string
        if not verse_key.isdigit():
            errors.append(f"Invalid verse key '{verse_key}' (must be integer string)")
            continue

        if not isinstance(verse_data, dict):
            errors.append(
                f"Verse {verse_key}: must be object, got {type(verse_data).__name__}"
            )
            continue

        actual_keys = set(verse_data.keys())

        # Check for typos in key names
        for key in actual_keys:
            for pattern, description in TYPO_PATTERNS:
                if re.match(pattern, key):
                    errors.append(f"Verse {verse_key}: key '{key}' has {description}")

        # Check for missing required Arabic layers
        missing_arabic = REQUIRED_ARABIC_LAYERS - actual_keys
        if missing_arabic:
            errors.append(f"Verse {verse_key}: missing Arabic layers {sorted(missing_arabic)}")

        # Validate each Arabic layer
        for arabic_layer in REQUIRED_ARABIC_LAYERS:
            if arabic_layer not in verse_data:
                continue

            value = verse_data[arabic_layer]

            # Must be string
            if not isinstance(value, str):
                errors.append(
                    f"Verse {verse_key} {arabic_layer}: must be string, got {type(value).__name__}"
                )
                continue

            # Must be non-empty
            if not value.strip():
                errors.append(f"Verse {verse_key} {arabic_layer}: content is empty")
                continue

            # Must contain actual Arabic script characters
            if not has_arabic_characters(value):
                errors.append(
                    f"Verse {verse_key} {arabic_layer}: no Arabic script characters found (may be transliteration or English)"
                )
                continue

            # Check word count
            word_count = count_arabic_words(value)
            if word_count < MIN_ARABIC_WORDS:
                errors.append(
                    f"Verse {verse_key} {arabic_layer}: only {word_count} words (minimum {MIN_ARABIC_WORDS})"
                )
            elif word_count > MAX_ARABIC_WORDS:
                errors.append(
                    f"Verse {verse_key} {arabic_layer}: {word_count} words exceeds maximum {MAX_ARABIC_WORDS}"
                )

    return errors


def main():
    log("Hook called")

    # Read hook input from stdin
    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError:
        log("No valid input, exiting")
        sys.exit(0)

    # Extract file path from tool_input
    tool_input = input_data.get("tool_input", {})
    file_path = tool_input.get("file_path", "")

    if not file_path:
        log("No file_path in input, exiting")
        sys.exit(0)

    filename = Path(file_path).name

    # Check if this is a file we should validate
    if not is_arabic_tafsir_file(file_path):
        log(f"Skipped (not arabic tafsir): {filename}")
        sys.exit(0)

    log(f"Validating: {filename}")

    # Run validation
    errors = validate_arabic_tafsir(file_path)

    if errors:
        log(f"FAILED: {filename} ({len(errors)} errors)")
        # Print to stdout so errors are fed back to agent as feedback (not blocking)
        print(f"\n⚠️ ARABIC TAFSIR VALIDATION ERRORS for {filename}:")
        print("")
        for i, error in enumerate(errors, 1):
            print(f"  {i}. {error}")
        print("")
        print("🔧 Please fix these issues in the output file and write it again.")
        print("")
        # Exit 0 to not block - agent will see errors and can fix them
        sys.exit(0)
    else:
        log(f"PASSED: {filename}")
        print(f"✅ Arabic tafsir validation passed: {filename}")
        sys.exit(0)


if __name__ == "__main__":
    main()
