#!/usr/bin/env python3
"""
Validate Urdu tafsir JSON files generated by the urdu-translator agent.
This script runs as a Claude Code PreToolUse hook.

Blocking validation: Errors output JSON with decision: "block" and exit code 2.
The agent must fix the issues and retry the Write until validation passes.

Exit codes:
- 0: Validation passed (Write operation proceeds)
- 2: Validation failed (Write operation BLOCKED - agent must fix and retry)

Output format (JSON to stdout):
- Success: {"decision": "allow"}
- Block: {"decision": "block", "reason": "error message"}
"""

import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Optional, Tuple

# Setup logging to file
LOG_DIR = Path(__file__).parent.parent.parent / "logs"
LOG_FILE = LOG_DIR / "urdu_validator.log"


def log(message: str):
    """Append a timestamped message to the log file."""
    try:
        LOG_DIR.mkdir(exist_ok=True)
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        with open(LOG_FILE, "a", encoding="utf-8") as f:
            f.write(f"[{timestamp}] {message}\n")
    except Exception:
        pass  # Silently fail if logging fails

# Required Urdu layer keys (Urdu-only output format)
REQUIRED_URDU_LAYERS = {"layer1_urdu", "layer2_urdu", "layer3_urdu", "layer4_urdu", "layer5_urdu"}

# Common typos to detect
TYPO_PATTERNS = [
    (r"^layar\d(_urdu)?$", "typo 'layar' instead of 'layer'"),
    (r"^layer\d\s+(_urdu)?$", "trailing whitespace in key"),
    (r"^Layer\d(_urdu)?$", "incorrect capitalization 'Layer' instead of 'layer'"),
    (r"^layer\s+\d(_urdu)?$", "space between 'layer' and number"),
    (r"^layre\d(_urdu)?$", "typo 'layre' instead of 'layer'"),
    (r"^layer\d_urdu_$", "trailing underscore in key"),
    (r"^layer\d_Urdu$", "incorrect capitalization '_Urdu' instead of '_urdu'"),
]

# Urdu script Unicode range (includes Arabic script used for Urdu)
URDU_ARABIC_PATTERN = re.compile(r'[\u0600-\u06FF\u0750-\u077F\uFB50-\uFDFF\uFE70-\uFEFF]')

# Word count limits for Urdu content (Urdu tends to be more concise)
MIN_URDU_WORDS = 50
MAX_URDU_WORDS = 600


def check_duplicate_keys(file_path: str) -> List[str]:
    """
    Check for duplicate keys in a JSON file.
    Python's json.load() silently ignores duplicates, so we need custom parsing.
    Returns a list of error messages for any duplicates found.
    """
    errors = []

    try:
        with open(file_path, "r", encoding="utf-8") as f:
            content = f.read()
    except Exception:
        return []  # File read errors handled elsewhere

    # Track duplicates at each nesting level
    def check_duplicates_hook(pairs: List[Tuple[str, any]]) -> dict:
        """Custom object_pairs_hook to detect duplicate keys."""
        seen = {}
        result = {}
        for key, value in pairs:
            if key in seen:
                # Record the duplicate - we'll extract context later
                seen[key] += 1
            else:
                seen[key] = 1
            result[key] = value

        # Check for duplicates
        for key, count in seen.items():
            if count > 1:
                errors.append(f"Duplicate key '{key}' found {count} times")

        return result

    try:
        json.loads(content, object_pairs_hook=check_duplicates_hook)
    except json.JSONDecodeError:
        pass  # JSON errors handled elsewhere

    return errors


def has_urdu_characters(text: str) -> bool:
    """Check if text contains Urdu/Arabic script characters."""
    return bool(URDU_ARABIC_PATTERN.search(text))


def count_urdu_words(text: str) -> int:
    """
    Count words in Urdu text.
    Urdu uses spaces between words similar to English.
    """
    # Split on whitespace and filter empty strings
    words = [w for w in text.split() if w.strip()]
    return len(words)


def is_urdu_tafsir_file(file_path: str) -> bool:
    """Check if the file is a Urdu tafsir output file in new_tafsir/ directory."""
    path = Path(file_path)
    # Must be in new_tafsir/ directory
    if "new_tafsir" not in str(path):
        return False
    # Match tafsir_*_v*-*_ur.json pattern (e.g., tafsir_103_v1-3_ur.json)
    if re.match(r"tafsir_\d+_v\d+-\d+_ur\.json$", path.name):
        return True
    # Also match legacy _urdu_added.json suffix
    if path.name.endswith("_urdu_added.json"):
        return True
    return False


def extract_expected_verses(file_path: str) -> Optional[List[int]]:
    """
    Extract expected verse range from filename.
    e.g., tafsir_103_v1-3_ur.json → [1, 2, 3]
    Returns None if pattern doesn't match.
    """
    path = Path(file_path)
    match = re.match(r"tafsir_\d+_v(\d+)-(\d+)_ur\.json$", path.name)
    if match:
        start = int(match.group(1))
        end = int(match.group(2))
        return list(range(start, end + 1))
    return None


def validate_urdu_content(content: str, file_path: str) -> List[str]:
    """
    Validate Urdu tafsir content that will be written (PreToolUse).
    Returns a list of error messages (empty if valid).
    """
    errors = []

    # 0. Check for duplicate keys in the raw content
    duplicate_errors = check_duplicate_keys_in_content(content)
    if duplicate_errors:
        errors.extend(duplicate_errors)

    # 1. Parse JSON
    try:
        data = json.loads(content)
    except json.JSONDecodeError as e:
        errors.append(f"Invalid JSON: {e}")
        return errors

    # 2. Root must be object
    if not isinstance(data, dict):
        errors.append(f"Root must be object, got {type(data).__name__}")
        return errors

    if len(data) == 0:
        errors.append("File contains no verses (empty object)")
        return errors

    # 3. Check all expected verses are present (based on filename)
    expected_verses = extract_expected_verses(file_path)
    if expected_verses:
        actual_verses = set(int(k) for k in data.keys() if k.isdigit())
        missing_verses = set(expected_verses) - actual_verses
        if missing_verses:
            missing_sorted = sorted(missing_verses)
            errors.append(f"Missing verses from expected range: {missing_sorted}")

    # 4. Validate each verse
    for verse_key, verse_data in data.items():
        # Check verse key is valid integer string
        if not verse_key.isdigit():
            errors.append(f"Invalid verse key '{verse_key}' (must be integer string)")
            continue

        if not isinstance(verse_data, dict):
            errors.append(
                f"Verse {verse_key}: must be object, got {type(verse_data).__name__}"
            )
            continue

        actual_keys = set(verse_data.keys())

        # Check for typos in key names
        for key in actual_keys:
            for pattern, description in TYPO_PATTERNS:
                if re.match(pattern, key):
                    errors.append(f"Verse {verse_key}: key '{key}' has {description}")

        # Check for missing required Urdu layers
        missing_urdu = REQUIRED_URDU_LAYERS - actual_keys
        if missing_urdu:
            errors.append(f"Verse {verse_key}: missing Urdu layers {sorted(missing_urdu)}")

        # Validate each Urdu layer
        for urdu_layer in REQUIRED_URDU_LAYERS:
            if urdu_layer not in verse_data:
                continue

            value = verse_data[urdu_layer]

            # Must be string
            if not isinstance(value, str):
                errors.append(
                    f"Verse {verse_key} {urdu_layer}: must be string, got {type(value).__name__}"
                )
                continue

            # Must be non-empty
            if not value.strip():
                errors.append(f"Verse {verse_key} {urdu_layer}: content is empty")
                continue

            # Must contain actual Urdu/Arabic script characters
            if not has_urdu_characters(value):
                errors.append(
                    f"Verse {verse_key} {urdu_layer}: no Urdu script characters found (may be transliteration or English)"
                )
                continue

            # Check word count
            word_count = count_urdu_words(value)
            if word_count < MIN_URDU_WORDS:
                errors.append(
                    f"Verse {verse_key} {urdu_layer}: only {word_count} words (minimum {MIN_URDU_WORDS})"
                )
            elif word_count > MAX_URDU_WORDS:
                errors.append(
                    f"Verse {verse_key} {urdu_layer}: {word_count} words exceeds maximum {MAX_URDU_WORDS}"
                )

    return errors


def check_duplicate_keys_in_content(content: str) -> List[str]:
    """
    Check for duplicate keys in JSON content string.
    Python's json.load() silently ignores duplicates, so we need custom parsing.
    Returns a list of error messages for any duplicates found.
    """
    errors = []

    # Track duplicates at each nesting level
    def check_duplicates_hook(pairs: List[Tuple[str, any]]) -> dict:
        """Custom object_pairs_hook to detect duplicate keys."""
        seen = {}
        result = {}
        for key, value in pairs:
            if key in seen:
                seen[key] += 1
            else:
                seen[key] = 1
            result[key] = value

        for key, count in seen.items():
            if count > 1:
                errors.append(f"Duplicate key '{key}' found {count} times")

        return result

    try:
        json.loads(content, object_pairs_hook=check_duplicates_hook)
    except json.JSONDecodeError:
        pass  # JSON errors handled elsewhere

    return errors


def output_block(reason: str):
    """Output JSON block decision and exit with code 2."""
    print(json.dumps({"decision": "block", "reason": reason}))
    sys.exit(2)


def output_allow():
    """Output JSON allow decision and exit with code 0."""
    print(json.dumps({"decision": "allow"}))
    sys.exit(0)


def main():
    log("Hook called")

    # Read hook input from stdin
    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError:
        log("No valid input, exiting")
        output_allow()

    # Extract file path from tool_input
    tool_input = input_data.get("tool_input", {})
    file_path = tool_input.get("file_path", "")

    if not file_path:
        log("No file_path in input, exiting")
        output_allow()

    filename = Path(file_path).name

    # Check for incorrect filename format (must end with _ur.json)
    if "new_tafsir" in file_path and filename.startswith("tafsir_") and not filename.endswith("_ur.json"):
        log(f"BLOCKED: {filename} does not end with _ur.json")
        output_block(
            f"Filename error: '{filename}' must end with '_ur.json'. "
            f"Use format: tafsir_<N>_v<start>-<end>_ur.json (e.g., tafsir_2_v1-20_ur.json)"
        )

    # Check if this is a file we should validate
    if not is_urdu_tafsir_file(file_path):
        log(f"Skipped (not urdu tafsir): {filename}")
        output_allow()

    log(f"Validating: {filename}")

    # For PreToolUse, the file doesn't exist yet - we can only validate filename format
    # Content validation happens via the content in tool_input
    content = tool_input.get("content", "")

    if not content:
        log(f"No content to validate for: {filename}")
        output_allow()

    # Validate the content that will be written
    errors = validate_urdu_content(content, file_path)

    if errors:
        log(f"FAILED: {filename} ({len(errors)} errors)")
        for i, error in enumerate(errors, 1):
            log(f"  {i}. {error}")
        # Format errors for the block reason
        error_list = "; ".join(f"({i}) {e}" for i, e in enumerate(errors, 1))
        output_block(f"Validation errors for {filename}: {error_list}")
    else:
        log(f"PASSED: {filename}")
        output_allow()


if __name__ == "__main__":
    main()
