#!/usr/bin/env python3
"""
Validate tafsir fragment JSON files generated by the tafsir-generator agent.
This script runs as a Claude Code PostToolUse hook.

Blocking validation: Errors cause exit code 1, which blocks the Write operation.
The agent must fix the issues and retry the Write until validation passes.

Exit codes:
- 0: Validation passed (Write operation succeeds)
- 1: Validation failed (Write operation BLOCKED - agent must fix and retry)
"""

import json
import re
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Tuple, Optional

LOG_DIR = Path(__file__).parent.parent.parent / "logs"
LOG_FILE = LOG_DIR / "tafsir_validator.log"


def log(message: str):
    """Append timestamped message to log file."""
    LOG_DIR.mkdir(exist_ok=True)
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(LOG_FILE, "a", encoding="utf-8") as f:
        f.write(f"[{timestamp}] {message}\n")

# Required layer keys (exact match)
REQUIRED_LAYERS = {"layer1", "layer2", "layer3", "layer4", "layer5"}

# Common typos to detect
TYPO_PATTERNS = [
    (r"^layar\d$", "typo 'layar' instead of 'layer'"),
    (r"^layer\d\s+$", "trailing whitespace in key"),
    (r"^Layer\d$", "incorrect capitalization 'Layer' instead of 'layer'"),
    (r"^layer\s+\d$", "space between 'layer' and number"),
    (r"^layre\d$", "typo 'layre' instead of 'layer'"),
    (r"^layer\d_$", "trailing underscore in key"),
]

# Word count limits
MIN_WORDS = 100
MAX_WORDS = 500


def parse_filename(filename: str) -> Optional[Tuple[int, int, int]]:
    """
    Parse tafsir fragment filename to extract surah and verse range.
    Returns (surah, start_verse, end_verse) or None if not a fragment file.
    """
    pattern = r"tafsir_(\d+)_v(\d+)-(\d+)\.json$"
    match = re.search(pattern, filename)
    if match:
        return int(match.group(1)), int(match.group(2)), int(match.group(3))
    return None


def validate_tafsir_fragment(file_path: str) -> List[str]:
    """
    Validate a tafsir fragment file.
    Returns a list of error messages (empty if valid).
    """
    errors = []
    path = Path(file_path)

    # Only validate files in new_tafsir/ directory
    if "new_tafsir" not in str(path):
        return []

    # Only validate .json files
    if not path.suffix == ".json":
        return []

    # Check if file exists
    if not path.exists():
        errors.append(f"File does not exist: {file_path}")
        return errors

    # 1. Parse JSON
    try:
        with open(path, "r", encoding="utf-8") as f:
            data = json.load(f)
    except json.JSONDecodeError as e:
        errors.append(f"Invalid JSON: {e}")
        return errors

    # 2. Root must be object
    if not isinstance(data, dict):
        errors.append(f"Root must be object, got {type(data).__name__}")
        return errors

    if len(data) == 0:
        errors.append("File contains no verses (empty object)")
        return errors

    # 3. Parse expected verse range from filename
    parsed = parse_filename(path.name)
    if parsed:
        surah, start_verse, end_verse = parsed
        expected_verses = set(str(v) for v in range(start_verse, end_verse + 1))
        actual_verses = set(data.keys())

        # Check for missing verses
        missing = expected_verses - actual_verses
        if missing:
            sorted_missing = sorted(missing, key=lambda x: int(x))
            errors.append(
                f"Missing verses from range v{start_verse}-{end_verse}: {sorted_missing}"
            )

        # Check for extra verses outside range
        extra = actual_verses - expected_verses
        if extra:
            sorted_extra = sorted(extra, key=lambda x: int(x) if x.isdigit() else 0)
            errors.append(
                f"Extra verses not in range v{start_verse}-{end_verse}: {sorted_extra}"
            )

    # 4-7. Validate each verse
    for verse_key, verse_data in data.items():
        # Check verse key is valid integer string
        if not verse_key.isdigit():
            errors.append(f"Invalid verse key '{verse_key}' (must be integer string)")
            continue

        if not isinstance(verse_data, dict):
            errors.append(
                f"Verse {verse_key}: must be object, got {type(verse_data).__name__}"
            )
            continue

        actual_keys = set(verse_data.keys())

        # Check for typos in key names
        for key in actual_keys:
            for pattern, description in TYPO_PATTERNS:
                if re.match(pattern, key):
                    errors.append(f"Verse {verse_key}: key '{key}' has {description}")

        # Check for missing required layers
        missing_layers = REQUIRED_LAYERS - actual_keys
        if missing_layers:
            errors.append(f"Verse {verse_key}: missing layers {sorted(missing_layers)}")

        # Validate each required layer
        for layer in REQUIRED_LAYERS:
            if layer not in verse_data:
                continue

            value = verse_data[layer]

            # Must be string
            if not isinstance(value, str):
                errors.append(
                    f"Verse {verse_key} {layer}: must be string, got {type(value).__name__}"
                )
                continue

            # Must be non-empty
            if not value.strip():
                errors.append(f"Verse {verse_key} {layer}: content is empty")
                continue

            # Check word count
            word_count = len(value.split())
            if word_count < MIN_WORDS:
                errors.append(
                    f"Verse {verse_key} {layer}: only {word_count} words (minimum {MIN_WORDS})"
                )
            elif word_count > MAX_WORDS:
                errors.append(
                    f"Verse {verse_key} {layer}: {word_count} words exceeds maximum {MAX_WORDS}"
                )

    return errors


def main():
    # Read hook input from stdin
    try:
        input_data = json.load(sys.stdin)
    except json.JSONDecodeError:
        # If stdin is empty or invalid, exit silently
        sys.exit(0)

    # Extract file path from tool_input
    tool_input = input_data.get("tool_input", {})
    file_path = tool_input.get("file_path", "")

    if not file_path:
        sys.exit(0)

    # Run validation
    errors = validate_tafsir_fragment(file_path)

    if errors:
        filename = Path(file_path).name
        log(f"FAILED: {filename} ({len(errors)} errors)")
        for i, error in enumerate(errors, 1):
            log(f"  {i}. {error}")
        # Print to stdout so errors are fed back to agent
        print(f"\n⚠️ TAFSIR VALIDATION ERRORS for {filename}:")
        print("")
        for i, error in enumerate(errors, 1):
            print(f"  {i}. {error}")
        print("")
        print("🔧 Write operation BLOCKED. Fix these issues and retry the Write.")
        print("")
        # Exit 1 to BLOCK - agent must fix errors before proceeding
        sys.exit(1)
    else:
        # Only print success for tafsir files we actually validated
        if "new_tafsir" in file_path and file_path.endswith(".json"):
            filename = Path(file_path).name
            log(f"PASSED: {filename}")
            print(f"✅ Tafsir validation passed: {filename}")
        sys.exit(0)


if __name__ == "__main__":
    main()
