//
//  SurahYusufDive.swift
//  Thaqalayn
//
//  Fixed content for the "Inside the Surah - Yusuf" experience. Rendered by
//  DeepDiveView; see docs/superpowers/specs/2026-07-07-surah-experience-design.md
//  and docs/plans/surah-experience/yusuf-script.md (approved master copy).
//
//  Trilingual (EN / UR / AR). Qur'an Arabic is verbatim from quran_data.json.
//  Generated deterministically from the approved script via the surah-experience
//  content pipeline (keyed EN/UR/AR + quran_data.json). No dua beat.
//  NOTE: UR/AR are English placeholders for now (translations deferred); regenerate
//  with yusuf_ur.json / yusuf_ar.json present to localize.
//

import SwiftUI

extension DeepDive {
    static let surahYusuf: DeepDive = DeepDive(
        id: "surah-yusuf",
        titleEn: "Yusuf",
        titleAr: "يُوسُف",
        subtitle: LocalizedText(en: "The best of stories - a dream, a pit, and the long road home", ur: "The best of stories - a dream, a pit, and the long road home", ar: "The best of stories - a dream, a pit, and the long road home"),
        sfSymbol: "moon.stars",
        estMinutes: 12,
        acts: [
            ActInfo(number: 1, ar: "الرُّؤْيَا", tr: "al-Ru'ya", name: LocalizedText(en: "The Dream", ur: "The Dream", ar: "The Dream")),
            ActInfo(number: 2, ar: "الْبَلَاء", tr: "al-Bala", name: LocalizedText(en: "The Test", ur: "The Test", ar: "The Test")),
            ActInfo(number: 3, ar: "اللِّقَاء", tr: "al-Liqa", name: LocalizedText(en: "The Reunion", ur: "The Reunion", ar: "The Reunion")),
        ],
        sections: [
            .open(
                kicker: LocalizedText(en: "INSIDE THE SURAH", ur: "INSIDE THE SURAH", ar: "INSIDE THE SURAH"),
                titleAr: "يُوسُف",
                titleEn: "Yusuf",
                subtitle: LocalizedText(en: "The Best of Stories", ur: "The Best of Stories", ar: "The Best of Stories"),
                line: LocalizedText(en: "A boy tells his father a dream, and his father tells him to keep it secret. So begins the best of stories - the long descent from a well in the dark to a throne in Egypt, and the God who was there the whole way down.", ur: "A boy tells his father a dream, and his father tells him to keep it secret. So begins the best of stories - the long descent from a well in the dark to a throne in Egypt, and the God who was there the whole way down.", ar: "A boy tells his father a dream, and his father tells him to keep it secret. So begins the best of stories - the long descent from a well in the dark to a throne in Egypt, and the God who was there the whole way down.")
            ),
            .orientation(
                eyebrow: LocalizedText(en: "Before you descend", ur: "Before you descend", ar: "Before you descend"),
                promise: LocalizedText(en: "This is the surah God sent down in the Year of Sorrow, to console His Prophet after he lost Khadija and Abu Talib - and He called it the best of stories. Below lies its whole arc, where every fall becomes a rise.", ur: "This is the surah God sent down in the Year of Sorrow, to console His Prophet after he lost Khadija and Abu Talib - and He called it the best of stories. Below lies its whole arc, where every fall becomes a rise.", ar: "This is the surah God sent down in the Year of Sorrow, to console His Prophet after he lost Khadija and Abu Talib - and He called it the best of stories. Below lies its whole arc, where every fall becomes a rise."),
                leaveWith: LocalizedText(en: "You will leave understanding the soul of the surah - that God-consciousness and beautiful patience carry a person from the bottom of a well to the throne - and why the Ahl al-Bayt taught that whoever keeps to its recitation is raised in the light of Yusuf.", ur: "You will leave understanding the soul of the surah - that God-consciousness and beautiful patience carry a person from the bottom of a well to the throne - and why the Ahl al-Bayt taught that whoever keeps to its recitation is raised in the light of Yusuf.", ar: "You will leave understanding the soul of the surah - that God-consciousness and beautiful patience carry a person from the bottom of a well to the throne - and why the Ahl al-Bayt taught that whoever keeps to its recitation is raised in the light of Yusuf.")
            ),
            .depths(
                act: 0, tag: LocalizedText(en: "The Map of the Surah", ur: "The Map of the Surah", ar: "The Map of the Surah"), reference: "Yusuf · 12",
                items: [
                    Depth(ar: "الْجُبّ", tr: "al-Jubb", label: LocalizedText(en: "The Well", ur: "The Well", ar: "The Well"), desc: LocalizedText(en: "Thrown into the dark by his own brothers, then raised out of it into the house of Egypt's ruler.", ur: "Thrown into the dark by his own brothers, then raised out of it into the house of Egypt's ruler.", ar: "Thrown into the dark by his own brothers, then raised out of it into the house of Egypt's ruler."), reference: "12:15", embodies: LocalizedText(en: "loss that becomes the road", ur: "loss that becomes the road", ar: "loss that becomes the road")),
                    Depth(ar: "السِّجْن", tr: "al-Sijn", label: LocalizedText(en: "The Prison", ur: "The Prison", ar: "The Prison"), desc: LocalizedText(en: "Cast down again by a lie he would not answer with sin, then raised from the cell to the throne.", ur: "Cast down again by a lie he would not answer with sin, then raised from the cell to the throne.", ar: "Cast down again by a lie he would not answer with sin, then raised from the cell to the throne."), reference: "12:33", embodies: LocalizedText(en: "the pit that becomes power", ur: "the pit that becomes power", ar: "the pit that becomes power")),
                    Depth(ar: "اللِّقَاء", tr: "al-Liqa", label: LocalizedText(en: "The Reunion", ur: "The Reunion", ar: "The Reunion"), desc: LocalizedText(en: "Long years of famine and grief, and then the family gathered and the childhood dream made real.", ur: "Long years of famine and grief, and then the family gathered and the childhood dream made real.", ar: "Long years of famine and grief, and then the family gathered and the childhood dream made real."), reference: "12:100", embodies: LocalizedText(en: "separation that becomes home", ur: "separation that becomes home", ar: "separation that becomes home")),
                ]
            ),
            .act(act: 1, connector: nil, line: LocalizedText(en: "It begins in a father's love and a night vision. A boy is favored, a dream is given, and a jealousy is kindled that will cast him down into the dark - where the story, and God's plan, truly begin.", ur: "It begins in a father's love and a night vision. A boy is favored, a dream is given, and a jealousy is kindled that will cast him down into the dark - where the story, and God's plan, truly begin.", ar: "It begins in a father's love and a night vision. A boy is favored, a dream is given, and a jealousy is kindled that will cast him down into the dark - where the story, and God's plan, truly begin."), bridge: nil),
            .verse(
                act: 1, tag: LocalizedText(en: "The Dream", ur: "The Dream", ar: "The Dream"), surah: 12, ayah: 4,
                arabic: "إِذْ قَالَ يُوسُفُ لِأَبِيهِ يَٰٓأَبَتِ إِنِّى رَأَيْتُ أَحَدَ عَشَرَ كَوْكَبًۭا وَٱلشَّمْسَ وَٱلْقَمَرَ رَأَيْتُهُمْ لِى سَٰجِدِينَ",
                translation: LocalizedText(en: "When Joseph said to his father, “O my father, I saw eleven stars, and the sun and the moon - I saw them prostrating to me.”", ur: "When Joseph said to his father, “O my father, I saw eleven stars, and the sun and the moon - I saw them prostrating to me.”", ar: ""),
                reference: "Yusuf · 12 : 4",
                reflection: LocalizedText(en: "One dream, and the whole surah is set in motion. The Ahl al-Bayt read the prostrating stars as a sign of spiritual rank, not worldly power, and said the believers are like stars that borrow their light from the suns of the prophets. Hold this dream the way Ya'qub told his son to hold it: a promise from God that will not come true for forty years.", ur: "One dream, and the whole surah is set in motion. The Ahl al-Bayt read the prostrating stars as a sign of spiritual rank, not worldly power, and said the believers are like stars that borrow their light from the suns of the prophets. Hold this dream the way Ya'qub told his son to hold it: a promise from God that will not come true for forty years.", ar: "One dream, and the whole surah is set in motion. The Ahl al-Bayt read the prostrating stars as a sign of spiritual rank, not worldly power, and said the believers are like stars that borrow their light from the suns of the prophets. Hold this dream the way Ya'qub told his son to hold it: a promise from God that will not come true for forty years.")
            ),
            .verse(
                act: 1, tag: LocalizedText(en: "Into the Well", ur: "Into the Well", ar: "Into the Well"), surah: 12, ayah: 15,
                arabic: "فَلَمَّا ذَهَبُوا۟ بِهِۦ وَأَجْمَعُوٓا۟ أَن يَجْعَلُوهُ فِى غَيَٰبَتِ ٱلْجُبِّ ۚ وَأَوْحَيْنَآ إِلَيْهِ لَتُنَبِّئَنَّهُم بِأَمْرِهِمْ هَٰذَا وَهُمْ لَا يَشْعُرُونَ",
                translation: LocalizedText(en: "So when they took him away and agreed to cast him into the bottom of the well… We revealed to him, “You will surely tell them of this deed of theirs, when they do not perceive who you are.”", ur: "So when they took him away and agreed to cast him into the bottom of the well… We revealed to him, “You will surely tell them of this deed of theirs, when they do not perceive who you are.”", ar: ""),
                reference: "Yusuf · 12 : 15",
                reflection: LocalizedText(en: "At the very bottom - betrayed, alone, a child in the dark - the first voice he hears is God's. Not rescue, but a promise: one day you will stand before them, and they will not know you. Imam Ali said God is nearest to His servant in the hardest hour. The well was not the end of the dream. It was the first step into it.", ur: "At the very bottom - betrayed, alone, a child in the dark - the first voice he hears is God's. Not rescue, but a promise: one day you will stand before them, and they will not know you. Imam Ali said God is nearest to His servant in the hardest hour. The well was not the end of the dream. It was the first step into it.", ar: "At the very bottom - betrayed, alone, a child in the dark - the first voice he hears is God's. Not rescue, but a promise: one day you will stand before them, and they will not know you. Imam Ali said God is nearest to His servant in the hardest hour. The well was not the end of the dream. It was the first step into it.")
            ),
            .verse(
                act: 1, tag: LocalizedText(en: "Beautiful Patience", ur: "Beautiful Patience", ar: "Beautiful Patience"), surah: 12, ayah: 18,
                arabic: "وَجَآءُو عَلَىٰ قَمِيصِهِۦ بِدَمٍۢ كَذِبٍۢ ۚ قَالَ بَلْ سَوَّلَتْ لَكُمْ أَنفُسُكُمْ أَمْرًۭا ۖ فَصَبْرٌۭ جَمِيلٌۭ ۖ وَٱللَّهُ ٱلْمُسْتَعَانُ عَلَىٰ مَا تَصِفُونَ",
                translation: LocalizedText(en: "And they brought his shirt stained with false blood. He said, “Rather, your souls have enticed you to something. So beautiful patience. And God is the One whose help is sought against what you describe.”", ur: "And they brought his shirt stained with false blood. He said, “Rather, your souls have enticed you to something. So beautiful patience. And God is the One whose help is sought against what you describe.”", ar: ""),
                reference: "Yusuf · 12 : 18",
                reflection: LocalizedText(en: "The shirt is whole, untorn by any wolf, and Ya'qub knows at once. Yet he does not rage. He says sabrun jamil, beautiful patience. The Ahl al-Bayt defined it as patience that complains to no one but God. Not a heart that does not break - a grief carried to the right door.", ur: "The shirt is whole, untorn by any wolf, and Ya'qub knows at once. Yet he does not rage. He says sabrun jamil, beautiful patience. The Ahl al-Bayt defined it as patience that complains to no one but God. Not a heart that does not break - a grief carried to the right door.", ar: "The shirt is whole, untorn by any wolf, and Ya'qub knows at once. Yet he does not rage. He says sabrun jamil, beautiful patience. The Ahl al-Bayt defined it as patience that complains to no one but God. Not a heart that does not break - a grief carried to the right door.")
            ),
            .act(act: 2, connector: LocalizedText(en: "You have watched him fall into the well, and heard God promise he would rise.", ur: "You have watched him fall into the well, and heard God promise he would rise.", ar: "You have watched him fall into the well, and heard God promise he would rise."), line: LocalizedText(en: "Now a second pit, and a subtler one: the ruler's house, its comfort, its temptation, and a prison that will hide, inside its walls, the next turn of God's plan.", ur: "Now a second pit, and a subtler one: the ruler's house, its comfort, its temptation, and a prison that will hide, inside its walls, the next turn of God's plan.", ar: "Now a second pit, and a subtler one: the ruler's house, its comfort, its temptation, and a prison that will hide, inside its walls, the next turn of God's plan."), bridge: nil),
            .verse(
                act: 2, tag: LocalizedText(en: "The Proof of His Lord", ur: "The Proof of His Lord", ar: "The Proof of His Lord"), surah: 12, ayah: 24,
                arabic: "وَلَقَدْ هَمَّتْ بِهِۦ ۖ وَهَمَّ بِهَا لَوْلَآ أَن رَّءَا بُرْهَٰنَ رَبِّهِۦ ۚ كَذَٰلِكَ لِنَصْرِفَ عَنْهُ ٱلسُّوٓءَ وَٱلْفَحْشَآءَ ۚ إِنَّهُۥ مِنْ عِبَادِنَا ٱلْمُخْلَصِينَ",
                translation: LocalizedText(en: "And she certainly desired him, and he would have desired her - had he not seen the proof of his Lord. So it was, that We might turn away from him evil and indecency. Indeed, he was among Our chosen servants.", ur: "And she certainly desired him, and he would have desired her - had he not seen the proof of his Lord. So it was, that We might turn away from him evil and indecency. Indeed, he was among Our chosen servants.", ar: ""),
                reference: "Yusuf · 12 : 24",
                reflection: LocalizedText(en: "The most delicate verse in the surah, and the Ahl al-Bayt read it exactly: he saw the proof of his Lord, and so he never inclined at all. This is isma - not a chain that holds a prophet back, but a purity so complete that sin finds no foothold. He was of the mukhlasin, the ones God has purified for Himself.", ur: "The most delicate verse in the surah, and the Ahl al-Bayt read it exactly: he saw the proof of his Lord, and so he never inclined at all. This is isma - not a chain that holds a prophet back, but a purity so complete that sin finds no foothold. He was of the mukhlasin, the ones God has purified for Himself.", ar: "The most delicate verse in the surah, and the Ahl al-Bayt read it exactly: he saw the proof of his Lord, and so he never inclined at all. This is isma - not a chain that holds a prophet back, but a purity so complete that sin finds no foothold. He was of the mukhlasin, the ones God has purified for Himself.")
            ),
            .verse(
                act: 2, tag: LocalizedText(en: "Prison, Not Sin", ur: "Prison, Not Sin", ar: "Prison, Not Sin"), surah: 12, ayah: 33,
                arabic: "قَالَ رَبِّ ٱلسِّجْنُ أَحَبُّ إِلَىَّ مِمَّا يَدْعُونَنِىٓ إِلَيْهِ ۖ وَإِلَّا تَصْرِفْ عَنِّى كَيْدَهُنَّ أَصْبُ إِلَيْهِنَّ وَأَكُن مِّنَ ٱلْجَٰهِلِينَ",
                translation: LocalizedText(en: "He said, “My Lord, prison is dearer to me than that to which they call me. And if You do not turn their scheming away from me, I may incline to them and be of the ignorant.”", ur: "He said, “My Lord, prison is dearer to me than that to which they call me. And if You do not turn their scheming away from me, I may incline to them and be of the ignorant.”", ar: ""),
                reference: "Yusuf · 12 : 33",
                reflection: LocalizedText(en: "A prophet who will not pretend he is safe from himself. He does not say “I am too pure to fall.” He says: keep me from it, or I might. Imam al-Baqir said the angels marveled that he chose the darkness of a prison over the darkness of sin. Strength is not never being tempted. It is knowing which darkness to fear.", ur: "A prophet who will not pretend he is safe from himself. He does not say “I am too pure to fall.” He says: keep me from it, or I might. Imam al-Baqir said the angels marveled that he chose the darkness of a prison over the darkness of sin. Strength is not never being tempted. It is knowing which darkness to fear.", ar: "A prophet who will not pretend he is safe from himself. He does not say “I am too pure to fall.” He says: keep me from it, or I might. Imam al-Baqir said the angels marveled that he chose the darkness of a prison over the darkness of sin. Strength is not never being tempted. It is knowing which darkness to fear.")
            ),
            .verse(
                act: 2, tag: LocalizedText(en: "The Soul That Commands", ur: "The Soul That Commands", ar: "The Soul That Commands"), surah: 12, ayah: 53,
                arabic: "۞ وَمَآ أُبَرِّئُ نَفْسِىٓ ۚ إِنَّ ٱلنَّفْسَ لَأَمَّارَةٌۢ بِٱلسُّوٓءِ إِلَّا مَا رَحِمَ رَبِّىٓ ۚ إِنَّ رَبِّى غَفُورٌۭ رَّحِيمٌۭ",
                translation: LocalizedText(en: "“And I do not absolve my own self. Indeed, the soul is ever commanding to evil, except those on whom my Lord has mercy. Indeed, my Lord is Forgiving, Merciful.”", ur: "“And I do not absolve my own self. Indeed, the soul is ever commanding to evil, except those on whom my Lord has mercy. Indeed, my Lord is Forgiving, Merciful.”", ar: ""),
                reference: "Yusuf · 12 : 53",
                reflection: LocalizedText(en: "Even now, cleared of all blame and about to be raised to power, Yusuf will not flatter himself. From this verse the Ahl al-Bayt drew the whole map of the self: the soul that commands evil, the soul that reproaches itself, and at last the soul at peace - and no one crosses that ground by their own strength, but only by the mercy of their Lord.", ur: "Even now, cleared of all blame and about to be raised to power, Yusuf will not flatter himself. From this verse the Ahl al-Bayt drew the whole map of the self: the soul that commands evil, the soul that reproaches itself, and at last the soul at peace - and no one crosses that ground by their own strength, but only by the mercy of their Lord.", ar: "Even now, cleared of all blame and about to be raised to power, Yusuf will not flatter himself. From this verse the Ahl al-Bayt drew the whole map of the self: the soul that commands evil, the soul that reproaches itself, and at last the soul at peace - and no one crosses that ground by their own strength, but only by the mercy of their Lord.")
            ),
            .act(
                act: 3, connector: LocalizedText(en: "You have seen him tested, kept pure, and raised at last to the throne.", ur: "You have seen him tested, kept pure, and raised at last to the throne.", ar: "You have seen him tested, kept pure, and raised at last to the throne."), line: LocalizedText(en: "Now the famine he foretold drives them back to Egypt: the brothers who sold him, standing before him for bread, not knowing the minister is the boy from the well. And an old father, still waiting, still refusing to despair.", ur: "Now the famine he foretold drives them back to Egypt: the brothers who sold him, standing before him for bread, not knowing the minister is the boy from the well. And an old father, still waiting, still refusing to despair.", ar: "Now the famine he foretold drives them back to Egypt: the brothers who sold him, standing before him for bread, not knowing the minister is the boy from the well. And an old father, still waiting, still refusing to despair."),
                bridge: BridgeVerse(
                    surah: 12, ayah: 87,
                    arabic: "يَٰبَنِىَّ ٱذْهَبُوا۟ فَتَحَسَّسُوا۟ مِن يُوسُفَ وَأَخِيهِ وَلَا تَا۟يْـَٔسُوا۟ مِن رَّوْحِ ٱللَّهِ ۖ إِنَّهُۥ لَا يَا۟يْـَٔسُ مِن رَّوْحِ ٱللَّهِ إِلَّا ٱلْقَوْمُ ٱلْكَٰفِرُونَ",
                    translation: LocalizedText(en: "“…and do not despair of God's relief. Indeed, no one despairs of God's relief except the disbelieving people.”", ur: "“…and do not despair of God's relief. Indeed, no one despairs of God's relief except the disbelieving people.”", ar: ""),
                    reference: "Yusuf · 12 : 87"
                )
            ),
            .verse(
                act: 3, tag: LocalizedText(en: "No Blame Upon You Today", ur: "No Blame Upon You Today", ar: "No Blame Upon You Today"), surah: 12, ayah: 92,
                arabic: "قَالَ لَا تَثْرِيبَ عَلَيْكُمُ ٱلْيَوْمَ ۖ يَغْفِرُ ٱللَّهُ لَكُمْ ۖ وَهُوَ أَرْحَمُ ٱلرَّٰحِمِينَ",
                translation: LocalizedText(en: "He said, “No blame upon you today. May God forgive you, and He is the most merciful of the merciful.”", ur: "He said, “No blame upon you today. May God forgive you, and He is the most merciful of the merciful.”", ar: ""),
                reference: "Yusuf · 12 : 92",
                reflection: LocalizedText(en: "He holds all the power now, and every right to revenge. Instead: no blame today. Not “I will try, in time, to forgive” - the door is thrown open the very moment it can be. And even his forgiveness he hands upward: may God forgive you. Mercy, at the exact instant it costs the most.", ur: "He holds all the power now, and every right to revenge. Instead: no blame today. Not “I will try, in time, to forgive” - the door is thrown open the very moment it can be. And even his forgiveness he hands upward: may God forgive you. Mercy, at the exact instant it costs the most.", ar: "He holds all the power now, and every right to revenge. Instead: no blame today. Not “I will try, in time, to forgive” - the door is thrown open the very moment it can be. And even his forgiveness he hands upward: may God forgive you. Mercy, at the exact instant it costs the most.")
            ),
            .narration(
                act: 3, tag: LocalizedText(en: "The Strength to Forgive", ur: "The Strength to Forgive", ar: "The Strength to Forgive"), source: LocalizedText(en: "Imam Ja'far al-Sadiq · Ilal al-Shara'i", ur: "Imam Ja'far al-Sadiq · Ilal al-Shara'i", ar: "Imam Ja'far al-Sadiq · Ilal al-Shara'i"),
                body: LocalizedText(en: "Standing at the height of his power over the very brothers who had thrown him into the well, Yusuf forgave them completely. Imam Ja'far al-Sadiq taught that this was not weakness but the highest form of strength - the strength to overcome the self's own hunger for revenge. The soul that once “commands to evil” is answered, at the last, by a mercy that asks nothing back.", ur: "Standing at the height of his power over the very brothers who had thrown him into the well, Yusuf forgave them completely. Imam Ja'far al-Sadiq taught that this was not weakness but the highest form of strength - the strength to overcome the self's own hunger for revenge. The soul that once “commands to evil” is answered, at the last, by a mercy that asks nothing back.", ar: "Standing at the height of his power over the very brothers who had thrown him into the well, Yusuf forgave them completely. Imam Ja'far al-Sadiq taught that this was not weakness but the highest form of strength - the strength to overcome the self's own hunger for revenge. The soul that once “commands to evil” is answered, at the last, by a mercy that asks nothing back."),
                reflection: LocalizedText(en: "To forgive from weakness is only to be unable to strike. To forgive from the throne - holding every power to punish, and setting it down - is the victory the whole surah has been climbing toward.", ur: "To forgive from weakness is only to be unable to strike. To forgive from the throne - holding every power to punish, and setting it down - is the victory the whole surah has been climbing toward.", ar: "To forgive from weakness is only to be unable to strike. To forgive from the throne - holding every power to punish, and setting it down - is the victory the whole surah has been climbing toward.")
            ),
            .verse(
                act: 3, tag: LocalizedText(en: "The Dream Fulfilled", ur: "The Dream Fulfilled", ar: "The Dream Fulfilled"), surah: 12, ayah: 100,
                arabic: "وَرَفَعَ أَبَوَيْهِ عَلَى ٱلْعَرْشِ وَخَرُّوا۟ لَهُۥ سُجَّدًۭا ۖ وَقَالَ يَٰٓأَبَتِ هَٰذَا تَأْوِيلُ رُءْيَٰىَ مِن قَبْلُ قَدْ جَعَلَهَا رَبِّى حَقًّۭا ۖ وَقَدْ أَحْسَنَ بِىٓ إِذْ أَخْرَجَنِى مِنَ ٱلسِّجْنِ وَجَآءَ بِكُم مِّنَ ٱلْبَدْوِ مِنۢ بَعْدِ أَن نَّزَغَ ٱلشَّيْطَٰنُ بَيْنِى وَبَيْنَ إِخْوَتِىٓ ۚ إِنَّ رَبِّى لَطِيفٌۭ لِّمَا يَشَآءُ ۚ إِنَّهُۥ هُوَ ٱلْعَلِيمُ ٱلْحَكِيمُ",
                translation: LocalizedText(en: "“…and they fell down before him in prostration. And he said, ‘O my father, this is the meaning of my vision of long ago. My Lord has made it real. He was good to me when He brought me out of the prison and brought you from the desert, after Satan had sown discord between me and my brothers…’”", ur: "“…and they fell down before him in prostration. And he said, ‘O my father, this is the meaning of my vision of long ago. My Lord has made it real. He was good to me when He brought me out of the prison and brought you from the desert, after Satan had sown discord between me and my brothers…’”", ar: ""),
                reference: "Yusuf · 12 : 100",
                reflection: LocalizedText(en: "Forty years later, the eleven and the sun and the moon bow down - exactly as the boy had dreamed. And notice how he tells it: he says God brought him out of the prison, and never once out of the well; he blames Satan for the rift, and names no brother. Even the memory, he tells with mercy.", ur: "Forty years later, the eleven and the sun and the moon bow down - exactly as the boy had dreamed. And notice how he tells it: he says God brought him out of the prison, and never once out of the well; he blames Satan for the rift, and names no brother. Even the memory, he tells with mercy.", ar: "Forty years later, the eleven and the sun and the moon bow down - exactly as the boy had dreamed. And notice how he tells it: he says God brought him out of the prison, and never once out of the well; he blames Satan for the rift, and names no brother. Even the memory, he tells with mercy.")
            ),
            .climax(
                act: 3, tag: LocalizedText(en: "Why It All Held", ur: "Why It All Held", ar: "Why It All Held"), source: LocalizedText("Yusuf · 12 : 90"),
                arabic: "إِنَّهُۥ مَن يَتَّقِ وَيَصْبِرْ فَإِنَّ ٱللَّهَ لَا يُضِيعُ أَجْرَ ٱلْمُحْسِنِينَ",
                translation: LocalizedText(en: "Indeed, whoever is mindful of God and is patient - God does not let the reward of those who do good be lost.", ur: "Indeed, whoever is mindful of God and is patient - God does not let the reward of those who do good be lost.", ar: ""),
                body: LocalizedText(en: "When his brothers finally ask, “Are you really Yusuf?”, he gives them the meaning of everything: God has favored us. And then the line that holds the whole surah together - whoever is mindful of God and patient, God does not let the reward of the doers of good be lost. The dream, the well, the slavery, the prison, the long wait: none of it was wasted. Not one hour of it.", ur: "When his brothers finally ask, “Are you really Yusuf?”, he gives them the meaning of everything: God has favored us. And then the line that holds the whole surah together - whoever is mindful of God and patient, God does not let the reward of the doers of good be lost. The dream, the well, the slavery, the prison, the long wait: none of it was wasted. Not one hour of it.", ar: "When his brothers finally ask, “Are you really Yusuf?”, he gives them the meaning of everything: God has favored us. And then the line that holds the whole surah together - whoever is mindful of God and patient, God does not let the reward of the doers of good be lost. The dream, the well, the slavery, the prison, the long wait: none of it was wasted. Not one hour of it."),
                reflection: LocalizedText(en: "This is the soul of the surah. Beautiful patience is not the absence of pain. It is the certainty that God is keeping an account no darkness can erase. Every pit was a road. Every year was counted.", ur: "This is the soul of the surah. Beautiful patience is not the absence of pain. It is the certainty that God is keeping an account no darkness can erase. Every pit was a road. Every year was counted.", ar: "This is the soul of the surah. Beautiful patience is not the absence of pain. It is the certainty that God is keeping an account no darkness can erase. Every pit was a road. Every year was counted.")
            ),
            .reflectionPrompt(
                tag: LocalizedText(en: "Return", ur: "Return", ar: "Return"),
                prompt: LocalizedText(en: "What is the well you are in?", ur: "What is the well you are in?", ar: "What is the well you are in?"),
                placeholder: LocalizedText(en: "A loss, a long wait, an injustice, a door that will not open…", ur: "A loss, a long wait, an injustice, a door that will not open…", ar: "A loss, a long wait, an injustice, a door that will not open…"),
                subline: LocalizedText(en: "You have walked the whole descent - the dream, the well, the prison, the reunion. Yusuf's story says no faithful patience is ever wasted. Before you go, name the pit you are in, and the dream you are being asked to keep trusting.", ur: "You have walked the whole descent - the dream, the well, the prison, the reunion. Yusuf's story says no faithful patience is ever wasted. Before you go, name the pit you are in, and the dream you are being asked to keep trusting.", ar: "You have walked the whole descent - the dream, the well, the prison, the reunion. Yusuf's story says no faithful patience is ever wasted. Before you go, name the pit you are in, and the dream you are being asked to keep trusting."),
                nextLabel: LocalizedText(en: "One last thing", ur: "One last thing", ar: "One last thing")
            ),
            .closing(
                tag: LocalizedText(en: "The Close", ur: "The Close", ar: "The Close"),
                titleAr: "يُوسُف",
                essence: LocalizedText(en: "At the summit of all his power, Yusuf asked God for one thing only: to die in submission, and to be joined with the righteous.", ur: "At the summit of all his power, Yusuf asked God for one thing only: to die in submission, and to be joined with the righteous.", ar: "At the summit of all his power, Yusuf asked God for one thing only: to die in submission, and to be joined with the righteous."),
                line: LocalizedText(en: "That is where the best of stories comes to rest - not on a throne, but on a heart that gave every rise back to God. Read the surah now in its own words, and let the dream unfold in full.", ur: "That is where the best of stories comes to rest - not on a throne, but on a heart that gave every rise back to God. Read the surah now in its own words, and let the dream unfold in full.", ar: "That is where the best of stories comes to rest - not on a throne, but on a heart that gave every rise back to God. Read the surah now in its own words, and let the dream unfold in full.")
            ),
        ]
    )
}

#if DEBUG
#Preview("Surah Yusuf experience") {
    DeepDiveView(dive: .surahYusuf, onClose: {})
}
#endif
