#!/bin/zsh
set -a; source ~/Documents/development/thaqalyn/.env; set +a
source ~/Documents/development/thaqalyn/.venv/bin/activate
cd ~/Documents/development/thaqalyn
NB=.claude/skills/paper-explainer/scripts/nano_banana.py
OUT=output/paper-explainer/hud/stills
REF=.claude/skills/paper-explainer/assets/style_ref_book.jpg
STYLE="Handmade papercraft diorama photographed with a macro lens, tilt-shift shallow depth of field, soft warm studio light. Everything is cut from layered cream, sand and kraft card with visible paper fibre and tiny cast shadows at every layer edge. Any figures are simple low-poly paper silhouettes with no faces. Accent palette: deep emerald and gold leaf. Vertical composition, dark warm bokeh background."
gen() { # id prompt [ref]
  local id=$1 p=$2 ref=$3
  if [ -n "$ref" ]; then python3 $NB --size 4K --aspect 9:16 --ref "$ref" --output $OUT/$id.png --prompt "$p"; else python3 $NB --size 4K --aspect 9:16 --output $OUT/$id.png --prompt "$p"; fi
  echo "DONE $id"
}
gen s01_book_mecca "$STYLE Same open book of layered cream card with a deep emerald and gold cover lying on a walnut desk as in the reference. Out of its open page rises a miniature paper city of Mecca at night: a small cube-shaped Kaaba wrapped in black paper with a gold band, low flat-roofed paper houses around it, paper hills behind, a paper crescent moon above. The top edge of the visible page carries the heading سورة هود in elegant gold calligraphy. The book fills the lower two thirds of the frame." "$REF"
gen s02_scroll_descends "$STYLE Seen from high above at dusk, a miniature paper city of Mecca with a small cube-shaped black paper Kaaba at its centre and low flat paper houses. From a paper sky of layered cloud shapes, one tall rolled paper scroll tied with a gold thread descends straight down in a single piece, casting a long soft shadow across the city. On the visible edge of the scroll the small numerals ١٢٣ are written in gold."
gen s03_seven_banners "$STYLE A long row of seven paper banners on thin wooden poles planted in a line across a rolling paper desert, receding into the distance. Each cream banner carries one name in dark ink calligraphy, in order from front to back: نوح, هود, صالح, إبراهيم, لوط, شعيب, موسى. In front of each banner stands a small crowd of faceless low-poly paper figures with their backs turned to the pole, walking away from it. Low warm sun, long shadows."
gen s04_ark_wave "$STYLE A large paper ark of layered kraft card sits on cracked, bone-dry paper ground with no water anywhere near it. At its foot a crowd of faceless low-poly paper figures point up at it and double over laughing. No one stands on the ark. Far on the horizon behind the ark, a towering wall of layered blue and cream paper wave curls forward beneath dark layered paper storm clouds, still distant. Strong directional light from the left."
gen s05_library_verse "$STYLE A cosy paper library nook: an open paper book on a wooden reading stand, and one single line of its page is lifted up out of the page as a separate raised card that reads ١١:١١٢ in dark ink. From the upper edge of the frame a paper sleeve and paper hand, no face visible, points at that raised card. Behind the stand, stacked paper volumes; the spine of one volume reads مجمع البيان in gold. Warm lamp light."
gen s06_fastaqim "$STYLE The single Arabic word فَاسْتَقِمْ built as enormous upright papercraft letters, several storeys tall, standing in a flat paper desert at low golden sun, casting very long shadows toward the camera. In the shade of the letters, a long row of small faceless low-poly paper figures stand perfectly straight, shoulder to shoulder. Camera low, near ground level."
gen s07_scale "$STYLE A papercraft balance scale of kraft card and gold thread standing on a wooden table. The left pan holds one small cream paper card with ١١٢ written on it in dark ink, and that pan is pressed all the way down. The right pan holds a heaped pile of grey and sand paper stones and is raised high. Nothing else on the table. Warm side light."
gen s08_heart_pillars "$STYLE A large papercraft heart made of many layered cream and rose card sheets, floating just above the ground, held up from beneath by seven upright paper pillars, each pillar clearly a tightly rolled paper scroll standing on end. A small hanging paper tag on the heart reads ١١:١٢٠ in gold. Soft gold light falling from directly above onto the heart, dark warm background."
gen s09_book_dawn "$STYLE Same open book of layered cream card with a deep emerald and gold cover lying on a walnut desk as in the reference, seen from slightly farther away so the whole book and part of the desk are visible. Out of its open page rises a miniature paper city of Mecca at dawn: a small cube-shaped black paper Kaaba with a gold band, low flat-roofed paper houses, paper hills, and a flat gold paper sun just above the hills throwing warm gold light across the whole city. The top edge of the visible page carries the heading سورة هود in gold calligraphy." "$REF"
gen s10_seeker "$STYLE Same walnut desk and same open book of layered cream card with a deep emerald and gold cover as in the reference, seen from behind a young faceless low-poly paper figure wearing a simple cream paper hoodie, seated at the desk. The figure holds up a small paper smartphone whose screen is a plain flat deep emerald green rectangle with nothing drawn on it. The open book with its small paper city lies on the desk in front of the figure. Warm lamp light from the left." "$REF"
echo ALL_DONE
